pipeline {
    agent any
    stages{
        stage('MVN_Steps'){
            steps{
                echo 'Running MVN Clean+Package...!!!!!'
                sh 'mvn clean package'
            }
        }
        stage('ListFiles'){
                    steps{
                        echo 'Files in directory...!!!!!'
                        sh 'pwd'
                        sh 'ls'
                    }
        }
        stage('DeployLocally'){
                    steps{
                        echo 'deploying locally!!'
                        sh 'nohup java -jar target/*.jar &'
                        sh 'sleep 5'
                    }
        }
        stage('SSH copy to remote') {
            steps {
                sshagent(['ssh_to_EC2_server_1']){
                    sh "scp -o StrictHostKeyChecking=no -P 22 target/*.jar ubuntu@${EC2_SERVER_1_IP}:/home/ubuntu/jar_images"

                }
            }
        }
    }
}