pipeline {
    agent any
    stages{
        stage('MVN_Steps'){
            steps{
                echo 'Running MVN Clean+Package...!!!!!'
                sh 'mvn clean package'
            }
        }
        stage('ListFiles'){
                    steps{
                        echo 'Files in directory...!!!!!'
                        sh 'pwd'
                        sh 'ls'
                    }
        }
        stage('DeployLocally'){
                    steps{
                        echo 'deploying locally!!'
                        sh 'nohup java -jar target/*.jar &'
                        sh 'sleep 20'
                    }
        }
        stage('SSH copy to remote') {
            steps {
                withCredentials([sshagent(['ssh_to_EC2_server_1'])]) {
                    script {
                        def ec2ServerIP = env.EC2_SERVER_1_IP
                        sh "scp /target/*.jar ${ec2ServerIP}:/home/ubuntu/jar_images"
                    }
                }
            }
        }
    }
}
