pipeline {
    agent any
    stages{
        stage('Clean'){
            steps{
                echo 'Running MVN Clean...!!!!!'
                sh 'mvn clear'
            }
        }
        stage('Package'){
                    steps{
                        echo 'Running MVN Package...!!!!!'
                        sh 'mvn package'
                    }
                }
    }
}